// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_f2Kj1vOaXp2PY97Vt6DdAGSex7XBcpQ',
    appId: '1:922005299348:web:e004a1fa3462c0fae21481',
    messagingSenderId: '922005299348',
    projectId: 'birthdayreminderapp-89e7d',
    authDomain: 'birthdayreminderapp-89e7d.firebaseapp.com',
    storageBucket: 'birthdayreminderapp-89e7d.firebasestorage.app',
    measurementId: 'G-ZPMRST3NV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC018Tshtn9IIGUNJyZPLC_NkXDFY-q-Jo',
    appId: '1:922005299348:android:790d58ef22da4ccee21481',
    messagingSenderId: '922005299348',
    projectId: 'birthdayreminderapp-89e7d',
    storageBucket: 'birthdayreminderapp-89e7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBef1XbgyhBWQ8fdg4NY6HHoQnNE7nqca0',
    appId: '1:922005299348:ios:45219e5cb0a7be05e21481',
    messagingSenderId: '922005299348',
    projectId: 'birthdayreminderapp-89e7d',
    storageBucket: 'birthdayreminderapp-89e7d.firebasestorage.app',
    iosBundleId: 'com.example.birthdayreminderapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBef1XbgyhBWQ8fdg4NY6HHoQnNE7nqca0',
    appId: '1:922005299348:ios:45219e5cb0a7be05e21481',
    messagingSenderId: '922005299348',
    projectId: 'birthdayreminderapp-89e7d',
    storageBucket: 'birthdayreminderapp-89e7d.firebasestorage.app',
    iosBundleId: 'com.example.birthdayreminderapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_f2Kj1vOaXp2PY97Vt6DdAGSex7XBcpQ',
    appId: '1:922005299348:web:87b8e0f6d256ee9ee21481',
    messagingSenderId: '922005299348',
    projectId: 'birthdayreminderapp-89e7d',
    authDomain: 'birthdayreminderapp-89e7d.firebaseapp.com',
    storageBucket: 'birthdayreminderapp-89e7d.firebasestorage.app',
    measurementId: 'G-D3ZBPJ9NS1',
  );
}
